version: "3.8"

networks:
  traefik:
    external: true
  wud:
    name: wud

services:
  wud:
    container_name: wud
    image: fmartinou/whats-up-docker 
    restart: unless-stopped
    networks:
      - traefik
      - wud
    ports:
      - 7330:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.wud.rule: Host(`wud.circacerulean.net`)
      traefik.http.routers.wud.entrypoints: web,web-tls
      traefik.http.routers.wud.tls: true
      traefik.http.routers.wud.tls.certresolver: letsencrypt
      traefik.http.services.wud.loadbalancer.server.port: 3000
