version: "3.8"

networks:
  traefik:
    external: true
  bookstack:
    name: bookstack

services:
  bookstack:
    container_name: bookstack
    image: lscr.io/linuxserver/bookstack
    restart: unless-stopped
    networks:
      - traefik
      - bookstack
    ports:
      - 6875:80
    volumes:
      - ./config:/config
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: bookstack.circacerulean.net
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: ${BOOKSTACK_DB_PASSWORD}
      DB_DATABASE: bookstackapp
    depends_on:
      - bookstack_db
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.bookstack.rule: Host(`bookstack.circacerulean.net`)
      traefik.http.routers.bookstack.entrypoints: web,web-tls
      traefik.http.routers.bookstack.tls: true
      traefik.http.routers.bookstack.tls.certresolver: letsencrypt
      traefik.http.routers.bookstack.tls.domains[0].main: circacerulean.net
      traefik.http.routers.bookstack.tls.domains[0].sans: *.circacerulean.net
      traefik.http.services.bookstack.loadbalancer.server.port: 80

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
      TZ: Etc/UTC
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
    volumes:
      - ./db_data:/config
    restart: unless-stopped
