version: "3.8"

networks:
  traefik:
    external: true
  postgres:
    external: true
  redis:
    external: true
  nextcloud:
    name: nextcloud

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    networks:
      - traefik
      - postgres
      - redis
      - nextcloud
    ports:
      - 7052:80
    volumes:
      - ./data/custom_apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - /mnt/carracosta/nextcloud/data:/var/www/html/data
    environment:
      NEXTCLOUD_ADMIN_USER: jg
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DOMAIN_NAME: nextcloud.circacerulean.net
      TRUSTED_PROXIES: "172.26.0.0/16"
      POSTGRES_HOST: postgres
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
      REDIS_HOST: redis
      APACHE_DISABLE_REWRITE_IP: 1
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.circacerulean.net`)
      traefik.http.routers.nextcloud.entrypoints: web,web-tls
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: letsencrypt
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
