version: "3.9"

networks:
  traefik:
    external: true
  cloudflared:
    name: cloudflared

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - traefik
      - cloudflared
