version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8089:80/tcp
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`pihole.circacerulean.net`)
      traefik.http.routers.pihole.entrypoints: web,web-tls
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.tls.certresolver: letsencrypt
      traefik.http.routers.pihole.tls.domains[0].main: circacerulean.net
      traefik.http.routers.pihole.tls.domains[1].sans: "*.circacerulean.net"
      #traefik.http.routers.pihole.middlewares: add-admin@docker
      #traefik.http.middlewares.add-admin.addprefix.prefix: "/admin"
      traefik.http.services.pihole.loadbalancer.server.port: 80
