version: "3.8"

networks:
  traefik:
    external: true
  postgres:
    external: true
  tandoor:
    name: tandoor

services:
  nginx_recipes:
    container_name: tandoor-nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    networks:
      - traefik
      - tandoor
    ports:
      - 7071:80
    volumes:
      - ./data/staticfiles:/static:ro
      - ./data/mediafiles:/media:ro
      - nginx_config:/etc/nginx/conf.d:ro
    env_file: ./.env
    depends_on:
      - web_recipes
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.tandoor.rule: Host(`tandoor.circacerulean.net`)
      traefik.http.routers.tandoor.entrypoints: web,web-tls
      traefik.http.routers.tandoor.tls: true
      traefik.http.routers.tandoor.tls.certresolver: letsencrypt
      traefik.http.services.tandoor.loadbalancer.server.port: 80

  web_recipes:
    container_name: tandoor-web
    image: vabene1111/recipes
    restart: unless-stopped
    networks:
      - postgres
      - tandoor
    volumes:
      - ./data/staticfiles:/opt/recipes/staticfiles
      - ./data/mediafiles:/opt/recipes/mediafiles
      - nginx_config:/opt/recipes/nginx/conf.d
    env_file: ./.env

volumes:
  nginx_config:
