version: '3.8'

networks:
  traefik:
    external: true
  emqx:
    external: true
  zigbee2mqtt:
    name: zigbee2mqtt

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    networks:
      - traefik
      - emqx
      - zigbee2mqtt
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8082:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.circacerulean.net`)
      traefik.http.routers.zigbee2mqtt.entrypoints: web,web-tls
      traefik.http.routers.zigbee2mqtt.tls: true
      traefik.http.routers.zigbee2mqtt.tls.certresolver: letsencrypt
      traefik.http.routers.zigbee2mqtt.tls.domains[0].main: circacerulean.net
      traefik.http.routers.zigbee2mqtt.tls.domains[0].sans: "*.circacerulean.net"
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080
