version: "3.8"

networks:
  traefik:
    external: true
  homeassistant:
    external: true
  vscode:
    name: vscode

services:
  vscode:
    container_name: vscode
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    networks:
      - traefik
      - homeassistant
      - vscode
    ports:
      - 8443:8443
    volumes:
      - ./config:/config
      - /mnt/sharpedo/docker:/mnt/docker
      - /mnt/sharpedo/docker/homeassistant/config:/mnt/homeassistant
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      DEFAULT_WORKSPACE: /mnt/homeassistant
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.vscode.rule: Host(`vscode.circacerulean.net`)
      traefik.http.routers.vscode.entrypoints: web,web-tls
      traefik.http.routers.vscode.tls: true
      traefik.http.routers.vscode.tls.certresolver: letsencrypt
      traefik.http.routers.vscode.tls.domains[0].main: circacerulean.net
      traefik.http.routers.vscode.tls.domains[0].sans: "*.circacerulean.net"
      traefik.http.services.vscode.loadbalancer.server.port: 8443 
